### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [GMOTGIT/GMOT-SSG#4]
You have two approaches to error handling:

1. print an error message, e.g., https://github.com/GMOTGIT/GMOT-SSG/blob/main/GMOT-SSG.js#L39
2. print an error object, e.g., https://github.com/GMOTGIT/GMOT-SSG/blob/main/GMOT-SSG.js#L52

I would improve these by doing the following:

```js
if(err) {
  // print a useful error message
  console.error('This is your error message explaining what happened, and how to fix...');
  // exit the program with a non-zero return code
  process.exit(1)
}
```

The latter part is useful when the program can't complete because it's missing some state or things are wrong somehow.

**Comment by GMOTGIT** [comment]
Thank you, I've updated the code.
