### ISSUE TITLE
Timing bug with mkdir logic

### ISSUE THREAD

**Issue by humphd** [GMOTGIT/GMOT-SSG#5]
You have a timing bug with your `mkdir` call in https://github.com/GMOTGIT/GMOT-SSG/blob/main/GMOT-SSG.js#L50.  Here you start a `mkdir` and that will happen in the future.  However, your code will immediately continue to https://github.com/GMOTGIT/GMOT-SSG/blob/main/GMOT-SSG.js#L89, and if the dir isn't created yet, you will have undefined behaviour (it might work, it might fail, it depends on timing).

A better approach is to either use `mkdirSync()` or to move your call to the rest of the code into the callback of `mkdir` and only run it after success.

**Comment by GMOTGIT** [comment]
Thank you, I've updated the code using the mkdirSync().
