### ISSUE TITLE
Use path module when working with paths

### ISSUE THREAD

**Issue by humphd** [GMOTGIT/GMOT-SSG#6]
You are treating paths as regular strings, which is going to break in lots of cases.  For example, https://github.com/GMOTGIT/GMOT-SSG/blob/main/htmlMaker.js#L5 to find the extension.  Use https://nodejs.org/api/path.html#path_path_extname_path.

**Comment by humphd** [comment]
Similar problem with https://github.com/GMOTGIT/GMOT-SSG/blob/main/htmlMaker.js#L69.  Use https://nodejs.org/api/path.html#path_path_dirname_path etc.

**Comment by humphd** [comment]
And here https://github.com/GMOTGIT/GMOT-SSG/blob/main/htmlMaker.js#L90

**Comment by GMOTGIT** [comment]
Thank you, I have implemented the path.
It is way easier than I was doing before.
Saved me lines of code.
