### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by humphd** [GMOTGIT/GMOT-SSG#7]
In https://github.com/GMOTGIT/GMOT-SSG/blob/main/htmlMaker.js#L76-L99 and https://github.com/GMOTGIT/GMOT-SSG/blob/main/htmlMaker.js#L104-L133 you do essentially the same thing, using different output directories.  Refactor this into a function that takes an argument for the path.  You should try not to repeat code: it's a sign that you need to create a reusable function.

**Comment by GMOTGIT** [comment]
I made a function to handle the writeFile function. Thank you so much for the feedback.
